apiVersion: apps/v1
kind: Deployment
metadata:
  name: earphones-deployment
  labels:
    app: earphones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: earphones
  template:
    metadata:
      labels:
        app: earphones
    spec:
      containers:
      - name: earphones
        image: 510648452144.dkr.ecr.us-east-1.amazonaws.com/shopping-site-earphones:7a48610da6a6a00e3a4b96585a4c5c7719ff0cb4
        ports:
        - containerPort: 80
