apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 510648452144.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:7a48610da6a6a00e3a4b96585a4c5c7719ff0cb4
        ports:
        - containerPort: 80
