apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlegrocery-deployment
  labels:
    app: googlegrocery
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlegrocery
  template:
    metadata:
      labels:
        app: googlegrocery
    spec:
      containers:
      - name: googlegrocery
        image: 510648452144.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlegrocery:2c23e0455a7585fe438e23066b133d3538b888da
        ports:
        - containerPort: 80
